### ISSUE TITLE
What's the best golang pattern to extend messages like sqlexp.MsgNotice?

### ISSUE THREAD

**Issue by shueybubbles** [golang-sql/sqlexp#1]
Currently, go-mssqldb throws away the SQL Server specific fields of an information token at https://github.com/microsoft/go-mssqldb/blob/39b1cff22838c5a0c85a5e8a196f05e2c462217d/token.go#L815

I'd like to communicate those fields to the callers that are SQL Server-aware. I don't know enough about go and type inheritance patterns to know what the best pattern for this requirement would be.

One problem is the `sqlexp` pattern of message handling depends on the client using a switch on the type name of the struct:

```go
	msg := retmsg.Message(ctx)
		switch m := msg.(type) {
		case sqlexp.MsgNotice:
			if !s.PrintError(m.Message, 10) {
				s.Format.AddMessage(m.Message)
			}
```

The only approach that comes to mind is defining an `mssql`-specific message struct that has the SQL Server fields in it and queueing that message in addition to the `sqlexp.MsgNotice`. The client app would then look for that message type instead of `sqlexp.MsgNotice` in its switch.
Other than that, is there some way the driver could send a message that would work with the existing message loop while allowing the caller to convert or cast the `sqlexp.MsgNotice` to a type that has the extra data in it? 

Perhaps `sqlexp` should revamp this model to use interfaces instead of structs.

@kardianos

**Comment by kardianos** [comment]
@shueybubbles Thank you for raising this.
What if that struct was defined as: type MsgNotice struct{ Message [fmt.Stringer](https://pkg.go.dev/fmt#Stringer) }

Then by default you can call String() on it, or if you know the specific type, you can type assert it.

Would you suggest something similar for: type MsgRowsAffected struct{ Count [int64](https://pkg.go.dev/builtin#int64) }, replace with an interface for the Count value?

Switching on interface is less ideal in go, due to duck typing. eg Go doesn't have any type inheritance.

**Comment by shueybubbles** [comment]
I think using an interface like `fmt.Stringer` for the Message would be reasonable. 
The implementation in go-mssqldb could be the [Error](https://github.com/microsoft/go-mssqldb/blob/39b1cff22838c5a0c85a5e8a196f05e2c462217d/error.go#L13) struct with a new `String()` method added to it which returns the `Message`. 

I don't know of any extra data that might go along with Rows Affected but there could be something in the future.

**Comment by kardianos** [comment]
Updated.

**Comment by shueybubbles** [comment]
thx!
